
files["data/kae/poi.lua"] = {
  read_globals = {
    -- "data/scripts/lib/utilities.lua"
    "check_parallel_pos",
  }
}

files["files/config.lua"] = {
  read_globals = {
  }
}

files["files/biome.lua"] = {
  read_globals = {
  }
}

files["files/eyes.lua"] = {
  read_globals = {
  }
}

files["files/i18n.lua"] = {
  read_globals = {
    -- "files/utility.lua"
    "to_title",
  }
}

files["files/orbs.lua"] = {
  read_globals = {
    -- "data/scripts/lib/utilities.lua"
    "orb_map_get",
  }
}

files["files/poi.lua"] = {
  read_globals = {
    -- "data/scripts/lib/utilities.lua"
    "check_parallel_pos",

    -- "files/eyes.lua"
    "get_eye_locations",
  }
}

files["files/temple.lua"] = {
  read_globals = {
    -- "data/scripts/lib/utilities.lua"
    "get_players",
  }
}

files["files/waypoint.lua"] = {
  read_globals = {
    -- "files/config.lua"
    "MOD_ID",
  }
}

files["settings.lua"] = {
  read_globals = {
    -- "data/scripts/lib/mod_settings.lua"
    "MOD_SETTING_SCOPE_RUNTIME",
    "mod_settings_get_version",
    "mod_settings_gui",
    "mod_settings_gui_count",
    "mod_settings_update",
  }
}

files["files/utility.lua"] = {
  read_globals = {
  }
}

files["init.lua"] = {
  read_globals = {
    -- "data/scripts/lib/utilities.lua"
    "get_players",

    -- "files/biome.lua"
    "get_biome_name",

    -- "files/config.lua"
    "MOD_ID",

    -- "files/orbs.lua"
    "init_orb_list",

    -- "files/temples.lua"
    "init_temple_list",

    -- "files/poi.lua"
    "BOSSES",
    "PLACES",
    "create_poi",
    "is_duplicate_poi",
    "is_valid_poi",
    "lookup_color",
    "player_in_temple",
    "get_world_width",
    "pos_abs_to_rel",
    "pos_rel_to_abs",
    "temple_get_exit",
    "update_eye_locations",
  }
}

read_globals = {
  "load_imgui",
  "print_error",
  "async",
  "wait",
  "EntityLoad",
  "EntityLoadEndGameItem",
  "EntityLoadCameraBound",
  "EntityLoadToEntity",
  "EntitySave",
  "EntityCreateNew",
  "EntityKill",
  "EntityGetIsAlive",
  "EntityAddComponent",
  "EntityRemoveComponent",
  "EntityGetAllComponents",
  "EntityGetComponent",
  "EntityGetFirstComponent",
  "EntityGetComponentIncludingDisabled",
  "EntityGetFirstComponentIncludingDisabled",
  "EntitySetTransform",
  "EntityApplyTransform",
  "EntityGetTransform",
  "EntityAddChild",
  "EntityGetAllChildren",
  "EntityGetParent",
  "EntityGetRootEntity",
  "EntityRemoveFromParent",
  "EntitySetComponentsWithTagEnabled",
  "EntitySetComponentIsEnabled",
  "EntityGetName",
  "EntitySetName",
  "EntityGetTags",
  "EntityGetWithTag",
  "EntityGetInRadius",
  "EntityGetInRadiusWithTag",
  "EntityGetClosest",
  "EntityGetClosestWithTag",
  "EntityGetWithName",
  "EntityAddTag",
  "EntityRemoveTag",
  "EntityHasTag",
  "EntityGetFilename",
  "ComponentGetValue",
  "ComponentGetValueBool",
  "ComponentGetValueInt",
  "ComponentGetValueFloat",
  "ComponentGetValueVector2",
  "ComponentSetValue",
  "ComponentSetValueVector2",
  "ComponentSetValueValueRange",
  "ComponentSetValueValueRangeInt",
  "ComponentSetMetaCustom",
  "ComponentGetMetaCustom",
  "ComponentObjectGetValue",
  "ComponentObjectGetValueBool",
  "ComponentObjectGetValueInt",
  "ComponentObjectGetValueFloat",
  "ComponentObjectSetValue",
  "ComponentAddTag",
  "ComponentRemoveTag",
  "ComponentHasTag",
  "ComponentGetValue2",
  "ComponentSetValue2",
  "ComponentObjectGetValue2",
  "ComponentObjectSetValue2",
  "EntityAddComponent2",
  "ComponentGetVectorSize",
  "ComponentGetVectorValue",
  "ComponentGetVector",
  "ComponentGetIsEnabled",
  "ComponentGetMembers",
  "ComponentObjectGetMembers",
  "ComponentGetTypeName",
  "GetUpdatedEntityID",
  "GetUpdatedComponentID",
  "SetTimeOut",
  "RegisterSpawnFunction",
  "SpawnActionItem",
  "SpawnStash",
  "SpawnApparition",
  "LoadEntityToStash",
  "AddMaterialInventoryMaterial",
  "GetMaterialInventoryMainMaterial",
  "GameScreenshake",
  "GameOnCompleted",
  "GameGiveAchievement",
  "GameDoEnding2",
  "GetParallelWorldPosition",
  "BiomeMapLoad_KeepPlayer",
  "BiomeMapLoad",
  "BiomeSetValue",
  "BiomeGetValue",
  "BiomeObjectSetValue",
  "BiomeVegetationSetValue",
  "BiomeMaterialSetValue",
  "BiomeMaterialGetValue",
  "GameIsIntroPlaying",
  "GameGetIsGamepadConnected",
  "GameGetWorldStateEntity",
  "GameGetPlayerStatsEntity",
  "GameGetOrbCountAllTime",
  "GameGetOrbCountThisRun",
  "GameGetOrbCollectedThisRun",
  "GameGetOrbCollectedAllTime",
  "GameClearOrbsFoundThisRun",
  "GameGetOrbCountTotal",
  "CellFactory_GetName",
  "CellFactory_GetType",
  "CellFactory_GetUIName",
  "CellFactory_GetAllLiquids",
  "CellFactory_GetAllSands",
  "CellFactory_GetAllGases",
  "CellFactory_GetAllFires",
  "CellFactory_GetAllSolids",
  "CellFactory_GetTags",
  "GameGetCameraPos",
  "GameSetCameraPos",
  "GameSetCameraFree",
  "GameGetCameraBounds",
  "GameRegenItemAction",
  "GameRegenItemActionsInContainer",
  "GameRegenItemActionsInPlayer",
  "GameKillInventoryItem",
  "GamePickUpInventoryItem",
  "GameGetAllInventoryItems",
  "GameDropAllItems",
  "GameDropPlayerInventoryItems",
  "GameDestroyInventoryItems",
  "GameIsInventoryOpen",
  "GameTriggerGameOver",
  "LoadPixelScene",
  "LoadBackgroundSprite",
  "GameCreateCosmeticParticle",
  "GameCreateParticle",
  "GameCreateSpriteForXFrames",
  "GameShootProjectile",
  "EntityInflictDamage",
  "EntityIngestMaterial",
  "EntityRemoveIngestionStatusEffect",
  "EntityAddRandomStains",
  "EntitySetDamageFromMaterial",
  "EntityRefreshSprite",
  "EntityGetWandCapacity",
  "GamePlayAnimation",
  "GameGetVelocityCompVelocity",
  "GameGetGameEffect",
  "GameGetGameEffectCount",
  "LoadGameEffectEntityTo",
  "GetGameEffectLoadTo",
  "SetPlayerSpawnLocation",
  "UnlockItem",
  "GameGetPotionColorUint",
  "EntityGetFirstHitboxCenter",
  "Raytrace",
  "RaytraceSurfaces",
  "RaytraceSurfacesAndLiquiform",
  "RaytracePlatforms",
  "FindFreePositionForBody",
  "GetSurfaceNormal",
  "DoesWorldExistAt",
  "StringToHerdId",
  "HerdIdToString",
  "GetHerdRelation",
  "EntityGetHerdRelation",
  "EntityGetHerdRelationSafe",
  "GenomeSetHerdId",
  "EntityGetClosestWormAttractor",
  "EntityGetClosestWormDetractor",
  "GamePrint",
  "GamePrintImportant",
  "DEBUG_GetMouseWorld",
  "DEBUG_MARK",
  "GameGetFrameNum",
  "GameGetRealWorldTimeSinceStarted",
  "IsPlayer",
  "IsInvisible",
  "GameIsDailyRun",
  "GameIsDailyRunOrDailyPracticeRun",
  "GameIsModeFullyDeterministic",
  "GlobalsSetValue",
  "GlobalsGetValue",
  "MagicNumbersGetValue",
  "SetWorldSeed",
  "SessionNumbersGetValue",
  "SessionNumbersSetValue",
  "SessionNumbersSave",
  "AutosaveDisable",
  "StatsGetValue",
  "StatsGlobalGetValue",
  "StatsBiomeGetValue",
  "StatsBiomeReset",
  "StatsLogPlayerKill",
  "CreateItemActionEntity",
  "GetRandomActionWithType",
  "GetRandomAction",
  "GameGetDateAndTimeUTC",
  "GameGetDateAndTimeLocal",
  "GameEmitRainParticles",
  "GameCutThroughWorldVertical",
  "BiomeMapSetSize",
  "BiomeMapGetSize",
  "BiomeMapSetPixel",
  "BiomeMapGetPixel",
  "BiomeMapConvertPixelFromUintToInt",
  "BiomeMapLoadImage",
  "BiomeMapLoadImageCropped",
  "BiomeMapGetVerticalPositionInsideBiome",
  "BiomeMapGetName",
  "SetRandomSeed",
  "Random",
  "Randomf",
  "RandomDistribution",
  "RandomDistributionf",
  "ProceduralRandom",
  "ProceduralRandomf",
  "ProceduralRandomi",
  "PhysicsAddBodyImage",
  "PhysicsAddBodyCreateBox",
  "PhysicsAddJoint",
  "PhysicsApplyForce",
  "PhysicsApplyTorque",
  "PhysicsApplyTorqueToComponent",
  "PhysicsApplyForceOnArea",
  "PhysicsRemoveJoints",
  "PhysicsSetStatic",
  "PhysicsGetComponentVelocity",
  "PhysicsGetComponentAngularVelocity",
  "PhysicsBody2InitFromComponents",
  "PhysicsVecToGameVec",
  "GameVecToPhysicsVec",
  "LooseChunk",
  "AddFlagPersistent",
  "RemoveFlagPersistent",
  "HasFlagPersistent",
  "GameAddFlagRun",
  "GameRemoveFlagRun",
  "GameHasFlagRun",
  "GameTriggerMusicEvent",
  "GameTriggerMusicCue",
  "GameTriggerMusicFadeOutAndDequeueAll",
  "GamePlaySound",
  "GameEntityPlaySound",
  "GameEntityPlaySoundLoop",
  "GameSetPostFxParameter",
  "GameUnsetPostFxParameter",
  "GameTextGetTranslatedOrNot",
  "GameTextGet",
  "GuiCreate",
  "GuiDestroy",
  "GuiStartFrame",
  "GuiOptionsAdd",
  "GuiOptionsRemove",
  "GuiOptionsClear",
  "GuiOptionsAddForNextWidget",
  "GuiColorSetForNextWidget",
  "GuiZSet",
  "GuiZSetForNextWidget",
  "GuiIdPush",
  "GuiIdPushString",
  "GuiIdPop",
  "GuiAnimateBegin",
  "GuiAnimateEnd",
  "GuiAnimateAlphaFadeIn",
  "GuiAnimateScaleIn",
  "GuiText",
  "GuiTextCentered",
  "GuiImage",
  "GuiImageNinePiece",
  "GuiButton",
  "GuiImageButton",
  "GuiSlider",
  "GuiTextInput",
  "GuiBeginAutoBox",
  "GuiEndAutoBoxNinePiece",
  "GuiTooltip",
  "GuiBeginScrollContainer",
  "GuiEndScrollContainer",
  "GuiLayoutBeginHorizontal",
  "GuiLayoutBeginVertical",
  "GuiLayoutAddHorizontalSpacing",
  "GuiLayoutAddVerticalSpacing",
  "GuiLayoutEnd",
  "GuiLayoutBeginLayer",
  "GuiLayoutEndLayer",
  "GuiGetScreenDimensions",
  "GuiGetTextDimensions",
  "GuiGetImageDimensions",
  "GuiGetPreviousWidgetInfo",
  "GameIsBetaBuild",
  "DebugGetIsDevBuild",
  "DebugEnableTrailerMode",
  "GameGetIsTrailerModeEnabled",
  "Debug_SaveTestPlayer",
  "DebugBiomeMapGetFilename",
  "EntityConvertToMaterial",
  "ConvertEverythingToGold",
  "ConvertMaterialEverywhere",
  "ConvertMaterialOnAreaInstantly",
  "GetDailyPracticeRunSeed",
  "ModIsEnabled",
  "ModGetActiveModIDs",
  "ModGetAPIVersion",
  "ModSettingGet",
  "ModSettingSet",
  "ModSettingGetNextValue",
  "ModSettingSetNextValue",
  "ModSettingRemove",
  "ModSettingGetCount",
  "ModSettingGetAtIndex",
  "StreamingGetIsConnected",
  "StreamingGetConnectedChannelName",
  "StreamingGetVotingCycleDurationFrames",
  "StreamingGetRandomViewerName",
  "StreamingGetSettingsGhostsNamedAfterViewers",
  "StreamingSetCustomPhaseDurations",
  "StreamingForceNewVoting",
  "StreamingSetVotingEnabled",
  "ModLuaFileAppend",
  "ModTextFileGetContent",
  "ModTextFileSetContent",
  "ModTextFileWhoSetContent",
  "ModMagicNumbersFileAdd",
  "ModMaterialsFileAdd",
  "ModRegisterAudioEventMappings",
  "ModDevGenerateSpriteUVsForDirectory",
  "RegisterProjectile",
  "RegisterGunAction",
  "RegisterGunShotEffects",
  "BeginProjectile",
  "EndProjectile",
  "BeginTriggerTimer",
  "BeginTriggerHitWorld",
  "BeginTriggerDeath",
  "EndTrigger",
  "SetProjectileConfigs",
  "StartReload",
  "ActionUsesRemainingChanged",
  "ActionUsed",
  "LogAction",
  "OnActionPlayed",
  "OnNotEnoughManaForAction",
  "BaabInstruction",
  "SetValueNumber",
  "GetValueNumber",
  "SetValueInteger",
  "GetValueInteger",
  "SetValueBool",
  "GetValueBool",
  "dofile",
  "dofile_once",
}

-- vim: set filetype=lua:
